name: MyFirstWorkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: List files in the repository
        run: |
            echo "The repository ${{ github.repository }} contains the following"
            tree
      literal_block: |
          Text blocks use four spaces as indentation. The entire
          block is assigned to the key 'literal_block' and keeps
          line breaks and empty lines.
  
          The block continuous until the next YAML element with the same
          indentation as the literal block.

